version: '2'
services:
  disconf_redis_1: 
    image: redis:6.0.8
    restart: always
  disconf_redis_2: 
    image: redis:6.0.8
    restart: always
  disconf_zookeeper: 
    image: zookeeper:3.3.6
    restart: always
  disconf_mysql: 
    image: 244699181/disconf_mysql:1.0.0
    environment:
      MYSQL_ROOT_PASSWORD: Heino@123
    restart: always
  disconf_tomcat: 
    image: 244699181/disconf_tomcat:1.0.0
    links: 
      - disconf_redis_1:redishost01 
      - disconf_redis_2:redishost02
      - disconf_zookeeper:zkhost
      - disconf_mysql:mysqlhost
    ports:
      - "8080:8080"
    restart: always
  disconf_nginx: 
    image: bolingcavalry/disconf_nginx:0.0.1
    links: 
      - disconf_tomcat:tomcathost 
    ports: 
      - "80:80" 
    restart: always
